### ISSUE TITLE
太字の間に表示された数式が数式モードにならない

### ISSUE THREAD

**Issue by king-p3nguin** [hirakuuuu/AtCoderToNotion#13]
# バグ
<https://atcoder.jp/contests/abc319/tasks/abc319_e>のページを生成したところ、太字の間に表示された数式が数式モードではなく太字のテキストとして表示されました。

![image](https://github.com/hirakuuuu/AtCoderToNotion/assets/103920010/995e33ef-5764-4da4-96ea-7f8d0086a219)

**Comment by hirakuuuu** [comment]
バグ報告ありがとうございます！
修正したものをアップロードしましたので、数日以内に反映されると思います。

**Comment by king-p3nguin** [comment]
ありがとうございます！
